# Generated by Django 5.2.7 on 2025-10-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Enlace a la imagen del producto', null=True, verbose_name='URL de la imagen'),
        ),
    ]
