# Generated by Django 5.2.7 on 2025-10-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0002_producto_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ELECTRONICA', 'Electrónica'), ('ROPA', 'Ropa'), ('ALACENA', 'Alacena'), ('REFRIGERADOS', 'Refrigerados'), ('HIGIENE, SALUD, Y BELLEZA', 'Higiene, salud, y belleza'), ('HOGAR', 'Hogar'), ('DEPORTES', 'Deportes'), ('OTROS', 'Otros')], default='OTROS', max_length=100),
        ),
    ]
