# Generated by Django 5.2.7 on 2025-10-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='id_proveedor',
        ),
    ]
