# Generated by Django 5.2.7 on 2025-10-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0005_categorias_productos_delete_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
